// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRV3oOXALx2yrokuST_CmggGQC6JeskNI',
    appId: '1:1052125950322:web:165642b4001ef8d4a32deb',
    messagingSenderId: '1052125950322',
    projectId: 'foodbook-beta-4d88f',
    authDomain: 'foodbook-beta-4d88f.firebaseapp.com',
    storageBucket: 'foodbook-beta-4d88f.firebasestorage.app',
    measurementId: 'G-2THDC95RM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDst1osEsKif2UlLjvW3dTgw47TM6M6zro',
    appId: '1:1052125950322:android:f5498050fa5b28fca32deb',
    messagingSenderId: '1052125950322',
    projectId: 'foodbook-beta-4d88f',
    storageBucket: 'foodbook-beta-4d88f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLKqZlWdoaUMcIP5jGZDQbM2IYP5jNgI',
    appId: '1:1052125950322:ios:5653c57fad1becf3a32deb',
    messagingSenderId: '1052125950322',
    projectId: 'foodbook-beta-4d88f',
    storageBucket: 'foodbook-beta-4d88f.firebasestorage.app',
    iosBundleId: 'com.example.foodbookBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRV3oOXALx2yrokuST_CmggGQC6JeskNI',
    appId: '1:1052125950322:web:d833bb025507ec30a32deb',
    messagingSenderId: '1052125950322',
    projectId: 'foodbook-beta-4d88f',
    authDomain: 'foodbook-beta-4d88f.firebaseapp.com',
    storageBucket: 'foodbook-beta-4d88f.firebasestorage.app',
    measurementId: 'G-0H2QP1STT8',
  );

}